strategies:
  - ALIPY_BMDR
  - ALIPY_CORESET_GREEDY
  - ALIPY_DENSITY_WEIGHTED
  - ALIPY_EXPECTED_ERROR_REDUCTION
  - ALIPY_GRAPH_DENSITY
  - ALIPY_QBC
  - ALIPY_RANDOM
  - ALIPY_SPAL
  - ALIPY_UNCERTAINTY_ENTROPY
  - ALIPY_UNCERTAINTY_LC
  - ALIPY_UNCERTAINTY_MM
  - LIBACT_DWUS
  - LIBACT_EER
  - LIBACT_QUIRE
  - LIBACT_UNCERTAINTY_ENT
  - LIBACT_UNCERTAINTY_LC
  - LIBACT_UNCERTAINTY_SM
  - OPTIMAL_GREEDY_10
  - OPTIMAL_GREEDY_20
  - PLAYGROUND_BANDIT
  - PLAYGROUND_GRAPH_DENSITY
  - PLAYGROUND_HIERARCHICAL_CLUSTER
  - PLAYGROUND_INFORMATIVE_DIVERSE
  - PLAYGROUND_KCENTER_GREEDY
  - PLAYGROUND_MARGIN
  - PLAYGROUND_MIXTURE
  - PLAYGROUND_UNIFORM
  - SKACTIVEML_COST_EMBEDDING
  - SKACTIVEML_DAL
  - SKACTIVEML_DWUS
  - SKACTIVEML_EXPECTED_AVERAGE_PRECISION
  - SKACTIVEML_MC_EER_LOG_LOSS
  - SKACTIVEML_MC_EER_MISCLASS_LOSS
  - SKACTIVEML_QBC
  - SKACTIVEML_QBC_VOTE_ENTROPY
  - SKACTIVEML_QUIRE
  - SKACTIVEML_US_ENTROPY
  - SKACTIVEML_US_LC
  - SKACTIVEML_US_MARGIN
  - SKACTIVEML_VOI
  - SKACTIVEML_VOI_LABELED
  - SKACTIVEML_VOI_UNLABELED
  - SMALLTEXT_BREAKINGTIES
  - SMALLTEXT_CONTRASTIVEAL
  - SMALLTEXT_EMBEDDINGKMEANS
  - SMALLTEXT_GREEDYCORESET
  - SMALLTEXT_LEASTCONFIDENCE
  - SMALLTEXT_LIGHTWEIGHTCORESET
  - SMALLTEXT_PREDICTIONENTROPY
  - SMALLTEXT_RANDOM
datasets:
  - Iris
  - wine_origin
  - glass
  - parkinsons
  - sonar
  - seeds
  - thyroid
  - statlog_heart
  - haberman
  - ionosphere
  - musk2
  - breast_cancer_wisconsin_original
  - wdbc
  - statlog_australian
  - diabetes
  - mammographic
  - statlog_vehicle
  - tic_tac_toe
  - statlog_germany
  - splice_junction
  - phishing
  - spambase
  - banana
  - ex8a
  - ex8b
  - musk1
  - phoneme
  - appendicitis
  - texture
  - ringnorm
  - twonorm
  - r15
  - d31
  - dwtc
  - xor_2x2
  - xor_4x4
  - xor_2x2_rotated
  - gaussian_balanced
  - gaussian_unbalanced
metrics:
  - weighted_precision.csv.xz
  - weighted_f1-score.csv.xz
  - weighted_recall.csv.xz
  - accuracy.csv.xz
data: "../../kp_test_int"
hyper: "../05_done_workload.csv"