strategies:
- ALIPY_RANDOM
- ALIPY_UNCERTAINTY_ENTROPY
- ALIPY_UNCERTAINTY_LC
- ALIPY_UNCERTAINTY_MM
datasets:
- appendicitis
- banana
- breast_cancer_wisconsin_original
- d31
- diabetes
metrices:
- biggest_drop_per_macro_recall_time_lag.csv.xz
- avg_dist_labeled.csv.xz
- biggest_drop_per_weighted_f1-score_time_lag.csv.xz
- nr_decreasing_al_cycles_per_accuracy_time_lag.csv.xz
hyperparameter: 05_done_workload.csv
data_dir : ../kp_test_int/strategies/