AMOUNT_OF_START_POINTS_TO_GENERATE: 10000
BASH_PARALLEL_RUNNERS: 10
COMPUTED_METRICS: null
CONFIG_FILE_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- mg
- exp_results
- kp_test
- 00_config.yaml
DATASETS_AMOUNT_OF_SPLITS: 5
DATASETS_COMPUTE_DISTANCES: true
DATASETS_DISTANCES_APPENDIX: _distances.csv.gzip
DATASETS_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- jg
- datasets
- clean
DATASETS_TEST_SIZE_PERCENTAGE: 0.4
DATASETS_TRAIN_TEST_SPLIT_APPENDIX: _split.csv
EVA_METRICS_TO_CORRELATE: null
EXPERIMENT_BASH_FILE_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- mg
- exp_results
- kp_test
- 02_bash.sh
EXPERIMENT_INSTALL_SLURM_DEP_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- mg
- exp_results
- kp_test
- 0x_install_deps.slurm
EXPERIMENT_PYTHON_PARALLEL_BASH_FILE_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- mg
- exp_results
- kp_test
- 02b_run_bash_parallel.py
EXPERIMENT_SLURM_CHAIN_JOB: !!python/object/apply:pathlib.PosixPath
- /
- home
- mg
- exp_results
- kp_test
- 02b_chain_job.sh
EXPERIMENT_SLURM_FILE_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- mg
- exp_results
- kp_test
- 02_slurm.slurm
EXPERIMENT_SLURM_GZIP_RESULTS_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- mg
- exp_results
- kp_test
- 02c_gzip_results.sh.slurm
EXPERIMENT_SLURM_TAR_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- mg
- exp_results
- kp_test
- 03_tar.slurm
EXPERIMENT_SYNC_AND_RUN_FILE_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- mg
- exp_results
- kp_test
- 04_sync_and_run.sh
EXPERIMENT_UPDATE_SLURM_DEP_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- mg
- exp_results
- kp_test
- 0x_update_deps.slurm
EXP_BATCH_SIZE: null
EXP_DATASET: null
EXP_GRID_BATCH_SIZE:
- 1
- 5
- 10
EXP_GRID_DATASET:
- !!python/object/apply:datasets.DATASET
  - 1
- !!python/object/apply:datasets.DATASET
  - 2
- !!python/object/apply:datasets.DATASET
  - 6
EXP_GRID_LEARNER_MODEL:
- !!python/object/apply:resources.data_types.LEARNER_MODEL
  - 8
- !!python/object/apply:resources.data_types.LEARNER_MODEL
  - 5
- !!python/object/apply:resources.data_types.LEARNER_MODEL
  - 1
EXP_GRID_NUM_QUERIES:
- 50
EXP_GRID_RANDOM_SEED:
- 0
EXP_GRID_START_POINT:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
EXP_GRID_STRATEGY:
- !!python/object/apply:resources.data_types.AL_STRATEGY
  - 1
- !!python/object/apply:resources.data_types.AL_STRATEGY
  - 2
- !!python/object/apply:resources.data_types.AL_STRATEGY
  - 33
- !!python/object/apply:resources.data_types.AL_STRATEGY
  - 34
- !!python/object/apply:resources.data_types.AL_STRATEGY
  - 8
- !!python/object/apply:resources.data_types.AL_STRATEGY
  - 45
- !!python/object/apply:resources.data_types.AL_STRATEGY
  - 43
- !!python/object/apply:resources.data_types.AL_STRATEGY
  - 70
EXP_GRID_TRAIN_TEST_BUCKET_SIZE:
- 0
- 1
- 2
- 3
- 4
EXP_LEARNER_MODEL: null
EXP_NUM_QUERIES: null
EXP_QUERY_SELECTION_RUNTIME_SECONDS_LIMIT: 600
EXP_RANDOM_SEED: null
EXP_RESULT_EXTRACTED_ZIP_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- mg
- exp_results
- beegfs
- ws
- '1'
- s5968580-al_olympics
- exp_results
- kp_test
EXP_RESULT_ZIP_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- mg
- exp_results.tar.gz
EXP_RESULT_ZIP_PATH_PREFIX: !!python/object/apply:pathlib.PosixPath
- beegfs
- ws
- '1'
- s5968580-al_olympics
- exp_results
- kp_test
EXP_START_POINT: null
EXP_STRATEGY: null
EXP_TITLE: kp_test
EXP_TRAIN_TEST_BUCKET_SIZE: null
EXP_UNIQUE_ID: null
GIT_COMMIT_HASH: 94dec5d97fda852f0ac80896175a2dd25bb1266d
INCLUDE_RESULTS_FROM: null
KAGGLE_DATASETS_YAML_CONFIG_PATH: !!python/object/apply:pathlib.PosixPath
- resources
- datasets.yaml
LOG_FILE: console
METRICS:
- Predicted_Samples
- Selected_Indices
- Standard_ML_Metrics
- Timing_Metrics
METRIC_RESULTS_FOLDER: null
NON_HPC_WORKLOAD_FILE_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- mg
- exp_results
- kp_test
- 01_non_hpc_workload.csv
N_JOBS: 1
OUTPUT_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- mg
- exp_results
- kp_test
OVERALL_DONE_WORKLOAD_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- mg
- exp_results
- kp_test
- 05_done_workload.csv
OVERALL_FAILED_WORKLOAD_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- mg
- exp_results
- kp_test
- 05_failed_workloads.csv
OVERALL_STARTED_OOM_WORKLOAD_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- mg
- exp_results
- kp_test
- 05_started_oom_workloads.csv
OVERWRITE_EXISTING_METRIC_FILES: false
RANDOM_SEED: 1312
RAW_DATASETS_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- jg
- datasets
- clean
- _raw
RECALCULATE_UPDATED_EXP_GRID: false
RERUN_FAILED_WORKLOADS: false
RESULTS_PATH: null
RUNNING_ENVIRONMENT: local
SAMPLES_CATEGORIZER: null
SEPARATE_HPC_LOCAL_WORKLOAD: false
SLURM_ITERATIONS_PER_BATCH: 100
SLURM_MEMORY: 2210
SLURM_NR_THREADS: 1
SLURM_OFFSET: 0
SLURM_TIME_LIMIT: '1:59:59'
WORKER_INDEX: null
WORKLOAD_FILE_PATH: !!python/object/apply:pathlib.PosixPath
- /
- home
- mg
- exp_results
- kp_test
- 01_workload.csv
