strategies:
- ALIPY_RANDOM
- ALIPY_UNCERTAINTY_ENTROPY
- ALIPY_UNCERTAINTY_LC
- ALIPY_UNCERTAINTY_MM
- OPTIMAL_GREEDY_10
- SKACTIVEML_DAL
- SMALLTEXT_EMBEDDINGKMEANS
- SMALLTEXT_LIGHTWEIGHTCORESET
datasets:
- Iris
- seeds
- wine_origin
metrices:
- biggest_drop_per_macro_recall_time_lag.csv.xz
- avg_dist_labeled.csv.xz
- auc_full_CLOSENESS_TO_DECISION_BOUNDARY.csv.xz
- biggest_drop_per_weighted_f1-score_time_lag.csv.xz
- auc_full_macro_recall_time_lag.csv.xz
- auc_full_query_selection_time.csv.xz
- nr_decreasing_al_cycles_per_accuracy_time_lag.csv.xz
- auc_full_class_distributions_chebyshev_added_up_time_lag.csv.xz
- weighted_recall_time_lag.csv.xz
- auc_full_class_distributions_chebyshev_batch.csv.xz
- auc_full_macro_f1-score.csv.xz
- auc_full_learner_training_time.csv.xz
- accuracy_time_lag.csv.xz
- auc_full_nr_decreasing_al_cycles_per_accuracy_time_lag.csv.xz
- auc_full_SWITCHES_CLASS_OFTEN_time_lag.csv.xz
- learner_training_time.csv.xz
- auc_full_weighted_precision.csv.xz
- auc_full_weighted_f1-score.csv.xz
- auc_full_nr_decreasing_al_cycles_per_weighted_recall_time_lag.csv.xz
- auc_full_avg_dist_unlabeled.csv.xz
- auc_full_nr_decreasing_al_cycles_per_macro_f1-score_time_lag.csv.xz
- weighted_precision_time_lag.csv.xz
- auc_full_avg_dist_batch_time_lag.csv.xz
- auc_full_biggest_drop_per_weighted_recall_time_lag.csv.xz
- nr_decreasing_al_cycles_per_macro_precision.csv.xz
- auc_full_weighted_f1-score_time_lag.csv.xz
- auc_full_nr_decreasing_al_cycles_per_accuracy.csv.xz
- auc_full_REGION_DENSITY_time_lag.csv.xz
- auc_full_AVERAGE_UNCERTAINTY.csv.xz
- nr_decreasing_al_cycles_per_weighted_recall.csv.xz
- auc_full_biggest_drop_per_weighted_precision_time_lag.csv.xz
- auc_full_macro_recall.csv.xz
- auc_full_macro_f1-score_time_lag.csv.xz
- class_distributions_chebyshev_added_up.csv.xz
- class_distributions_manhattan_added_up_time_lag.csv.xz
- weighted_precision.csv.xz
- auc_full_biggest_drop_per_macro_recall_time_lag.csv.xz
- auc_full_CLOSENESS_TO_SAMPLES_OF_SAME_CLASS_kNN.csv.xz
- auc_full_CLOSENESS_TO_SAMPLES_OF_OTHER_CLASS.csv.xz
- auc_full_biggest_drop_per_macro_f1-score_time_lag.csv.xz
- auc_full_biggest_drop_per_macro_precision.csv.xz
- auc_full_biggest_drop_per_weighted_recall.csv.xz
- auc_full_CLOSENESS_TO_CLUSTER_CENTER_time_lag.csv.xz
- nr_decreasing_al_cycles_per_weighted_f1-score.csv.xz
- biggest_drop_per_weighted_precision.csv.xz
- biggest_drop_per_weighted_precision_time_lag.csv.xz
- auc_full_class_distributions_manhattan_added_up_time_lag.csv.xz
- avg_dist_unlabeled_time_lag.csv.xz
- auc_full_biggest_drop_per_accuracy.csv.xz
- auc_full_nr_decreasing_al_cycles_per_weighted_precision.csv.xz
- auc_full_class_distributions_chebyshev_added_up.csv.xz
- nr_decreasing_al_cycles_per_weighted_f1-score_time_lag.csv.xz
- biggest_drop_per_weighted_recall.csv.xz
- biggest_drop_per_weighted_recall_time_lag.csv.xz
- auc_full_CLOSENESS_TO_SAMPLES_OF_SAME_CLASS_time_lag.csv.xz
- auc_full_IMPROVES_ACCURACY_BY.csv.xz
- biggest_drop_per_macro_recall.csv.xz
- class_distributions_manhattan_added_up.csv.xz
- auc_full_CLOSENESS_TO_SAMPLES_OF_OTHER_CLASS_kNN.csv.xz
- auc_full_SWITCHES_CLASS_OFTEN.csv.xz
- mismatch_train_test_time_lag.csv.xz
- avg_dist_labeled_time_lag.csv.xz
- auc_full_biggest_drop_per_macro_recall.csv.xz
- macro_precision.csv.xz
- auc_full_CLOSENESS_TO_SAMPLES_OF_SAME_CLASS.csv.xz
- auc_full_nr_decreasing_al_cycles_per_weighted_precision_time_lag.csv.xz
- auc_full_biggest_drop_per_weighted_precision.csv.xz
- auc_full_avg_dist_batch.csv.xz
- class_distributions_chebyshev_batch.csv.xz
- biggest_drop_per_macro_f1-score.csv.xz
- auc_full_weighted_precision_time_lag.csv.xz
- auc_full_nr_decreasing_al_cycles_per_macro_recall.csv.xz
- auc_full_macro_precision.csv.xz
- nr_decreasing_al_cycles_per_macro_recall_time_lag.csv.xz
- auc_full_learner_training_time_time_lag.csv.xz
- class_distributions_chebyshev_batch_time_lag.csv.xz
- auc_full_CLOSENESS_TO_SAMPLES_OF_SAME_CLASS_kNN_time_lag.csv.xz
- auc_full_CLOSENESS_TO_CLUSTER_CENTER.csv.xz
- macro_f1-score.csv.xz
- auc_full_REGION_DENSITY.csv.xz
- auc_full_COUNT_WRONG_CLASSIFICATIONS.csv.xz
- auc_full_accuracy_time_lag.csv.xz
- avg_dist_batch_time_lag.csv.xz
- auc_full_class_distributions_chebyshev_batch_time_lag.csv.xz
- auc_full_nr_decreasing_al_cycles_per_macro_precision_time_lag.csv.xz
- avg_dist_batch.csv.xz
- auc_full_nr_decreasing_al_cycles_per_weighted_f1-score_time_lag.csv.xz
- auc_full_nr_decreasing_al_cycles_per_macro_f1-score.csv.xz
- nr_decreasing_al_cycles_per_weighted_recall_time_lag.csv.xz
- auc_full_MELTING_POT_REGION.csv.xz
- query_selection_time_time_lag.csv.xz
- auc_full_biggest_drop_per_accuracy_time_lag.csv.xz
- avg_dist_unlabeled.csv.xz
- nr_decreasing_al_cycles_per_weighted_precision_time_lag.csv.xz
- nr_decreasing_al_cycles_per_macro_precision_time_lag.csv.xz
- macro_recall_time_lag.csv.xz
- weighted_recall.csv.xz
- auc_full_avg_dist_unlabeled_time_lag.csv.xz
- auc_full_query_selection_time_time_lag.csv.xz
- biggest_drop_per_macro_precision_time_lag.csv.xz
- biggest_drop_per_macro_f1-score_time_lag.csv.xz
- auc_full_CLOSENESS_TO_SAMPLES_OF_OTHER_CLASS_kNN_time_lag.csv.xz
- auc_full_nr_decreasing_al_cycles_per_weighted_recall.csv.xz
- learner_training_time_time_lag.csv.xz
- auc_full_AVERAGE_UNCERTAINTY_time_lag.csv.xz
- auc_full_MELTING_POT_REGION_time_lag.csv.xz
- auc_full_biggest_drop_per_weighted_f1-score.csv.xz
- auc_full_CLOSENESS_TO_SAMPLES_OF_OTHER_CLASS_time_lag.csv.xz
- macro_precision_time_lag.csv.xz
- auc_full_biggest_drop_per_weighted_f1-score_time_lag.csv.xz
- auc_full_CLOSENESS_TO_DECISION_BOUNDARY_time_lag.csv.xz
- nr_decreasing_al_cycles_per_weighted_precision.csv.xz
- query_selection_time.csv.xz
- macro_f1-score_time_lag.csv.xz
- nr_decreasing_al_cycles_per_macro_f1-score.csv.xz
- auc_full_nr_decreasing_al_cycles_per_macro_recall_time_lag.csv.xz
- auc_full_weighted_recall.csv.xz
- class_distributions_chebyshev_added_up_time_lag.csv.xz
- auc_full_mismatch_train_test.csv.xz
- class_distributions_manhattan_batch.csv.xz
- accuracy.csv.xz
- nr_decreasing_al_cycles_per_macro_recall.csv.xz
- biggest_drop_per_macro_precision.csv.xz
- biggest_drop_per_accuracy_time_lag.csv.xz
- nr_decreasing_al_cycles_per_accuracy.csv.xz
- class_distributions_manhattan_batch_time_lag.csv.xz
- auc_full_biggest_drop_per_macro_f1-score.csv.xz
- macro_recall.csv.xz
- auc_full_OUTLIERNESS_time_lag.csv.xz
- auc_full_COUNT_WRONG_CLASSIFICATIONS_time_lag.csv.xz
- auc_full_accuracy.csv.xz
- auc_full_class_distributions_manhattan_batch.csv.xz
- biggest_drop_per_accuracy.csv.xz
- auc_full_OUTLIERNESS.csv.xz
- auc_full_IMPROVES_ACCURACY_BY_time_lag.csv.xz
- auc_full_avg_dist_labeled_time_lag.csv.xz
- auc_full_class_distributions_manhattan_added_up.csv.xz
- auc_full_biggest_drop_per_macro_precision_time_lag.csv.xz
- auc_full_nr_decreasing_al_cycles_per_macro_precision.csv.xz
- auc_full_macro_precision_time_lag.csv.xz
- auc_full_nr_decreasing_al_cycles_per_weighted_f1-score.csv.xz
- auc_full_avg_dist_labeled.csv.xz
- weighted_f1-score.csv.xz
- mismatch_train_test.csv.xz
- nr_decreasing_al_cycles_per_macro_f1-score_time_lag.csv.xz
- auc_full_class_distributions_manhattan_batch_time_lag.csv.xz
- weighted_f1-score_time_lag.csv.xz
- auc_full_mismatch_train_test_time_lag.csv.xz
- biggest_drop_per_weighted_f1-score.csv.xz
- auc_full_weighted_recall_time_lag.csv.xz
hyperparameter: new/05_done_workload.csv
