strategies:
- ALIPY_RANDOM
- ALIPY_UNCERTAINTY_ENTROPY
- ALIPY_UNCERTAINTY_LC
- ALIPY_UNCERTAINTY_MM
- OPTIMAL_GREEDY_10
- SKACTIVEML_DAL
- SMALLTEXT_EMBEDDINGKMEANS
- SMALLTEXT_LIGHTWEIGHTCORESET
datasets:
- Iris
- seeds
- wine_origin
metrices: []
